# Generated by Django 3.1.1 on 2020-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201027_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Convener', 'Convener'), ('Co-convener', 'Co-convener'), ('Member', 'Member')], max_length=100),
        ),
    ]
