# Generated by Django 3.1.1 on 2020-11-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201027_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('Lead', 'Lead'), ('Co-Lead', 'Co-Lead'), ('Member', 'Member')], max_length=100)),
                ('profilepic', models.ImageField(blank=True, upload_to='team-profilepics')),
                ('github', models.URLField(blank=True, max_length=1000)),
                ('linkedIn', models.URLField(blank=True, max_length=1000)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
