# Generated by Django 3.1.5 on 2021-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201120_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Co-Lead', 'Co-Lead'), ('Member', 'Member'), ('Coordinator', 'Coordinator')], max_length=100),
        ),
    ]
