# Generated by Django 3.1.1 on 2020-10-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='faculty',
        ),
    ]
