# Generated by Django 3.1.5 on 2021-01-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='events-poster')),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('long_description', models.TextField(blank=True)),
                ('prize', models.IntegerField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('rules_doc', models.FileField(blank=True, upload_to='rules')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('google_form_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Convener', 'Convener'), ('Co-convener', 'Co-convener'), ('Committee-Coordinator', 'Committee-Coordinator')], max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
