# Generated by Django 3.1.1 on 2020-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Convener', 'Convener'), ('Co-convener', 'Co-convener'), ('Member', 'Member')], max_length=100),
        ),
    ]
