# Generated by Django 3.1.5 on 2021-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201120_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_form_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
