# Generated by Django 3.1.5 on 2021-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210105_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook',
            field=models.URLField(blank=True),
        ),
    ]
