# Generated by Django 3.1.5 on 2021-01-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210109_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_size',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventmember', to='events.event'),
        ),
    ]
