# Generated by Django 3.1.5 on 2021-01-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210113_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
