# Generated by Django 3.1.5 on 2021-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210114_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Convener', 'Convener'), ('Co-convener', 'Co-convener'), ('Committee-Coordinator', 'Committee-Coordinator')], max_length=100),
        ),
    ]
