# Generated by Django 3.1.1 on 2020-10-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individialphotosubmission',
            old_name='youtube_link',
            new_name='link',
        ),
    ]
