# Generated by Django 3.1.1 on 2020-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20201027_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individialphotosubmission',
            name='link',
        ),
        migrations.AddField(
            model_name='individialphotosubmission',
            name='photo',
            field=models.ImageField(null=True, upload_to='submissions'),
        ),
    ]
