# Generated by Django 3.1.1 on 2020-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20201027_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teamsubmission',
            name='number',
        ),
        migrations.AddField(
            model_name='individialphotosubmission',
            name='photo_comp',
            field=models.ImageField(null=True, upload_to='submissions'),
        ),
    ]
