# Generated by Django 3.1.1 on 2020-10-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20201029_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsubmission',
            name='phone',
        ),
    ]
